### ISSUE TITLE
not running properly , Please help!!!!!!

### ISSUE THREAD

**Issue by cornusandu** [shivasiddharth/headless-alexa-avs-sample-app#4]
Hello guys,
Please keep in mind that i am a really noob considering Raspbian and linux. I managed to install alexa all the way thru but when i try to install headless alexa autostart at the last point when running : sudo /home/pi/headless-alexa-avs-sample-app/installer.sh.  it just jump to pi@raspberry after showing ;continuing; . It should first have all the created symlink . after i run the sudo /home/pi/headless-alexa-avs-sample-app/installer.sh Alexa keeps saying every 20 seconds Hello and voice awake is not running unless i open a command window and run the kitt-ai command. Any idea guys? I am really at the end of my rope here.

**Comment by shivasiddharth** [comment]
I have set the default folder location in the scripts to dektop, if you have the alexa-avs-sample app folder in /home/pi directory, then you need to change the directory in the bash scripts.

**Comment by cornusandu** [comment]
Yes, in order to be exactly like your video I installed Alexa-Ava-sample in /home/pi instead of Desktop and I have changed the three script files from ~/Desktop/ to /home/pi/

**Comment by cornusandu** [comment]
It is funny because it says every  20 sec “ Hello” like is starting every 20-30 sec. and it will wake up on my call”Alexa” only if I open only one command window to start kitt-ai . After I run kitt-ai it will still say “Hello “ every 20-30 sec.

**Comment by shivasiddharth** [comment]
can you try removing sudo in that wakeword.sh script and restart the service using:
`sudo systemctl restart wakeword.service`

**Comment by cornusandu** [comment]
Sorry for the late reply. Yessss it was the sudo removal. I also made the path : /home/pi/Desktop/.
Thank you very much for your help.
